### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by andrewhamon** [sigwebucf/resume-upload#1]

**Comment by stevenpetryk** [comment]
This is GitHub! Congratulations on joining.

GitHub is a platform where individuals and organizations can collaborate on projects that are tracked using the Git source code management tool. It allows for users to attach metadata to particular events in Git (such as commenting on line-by-line diffs and commits), as well as helps to track project goals through the use of milestones and issues.

What you've just done is opened up an [issue](https://guides.github.com/features/issues/). Issues can be assigned to users who are a part of the project – these users are called "collaborators". When reading issues on GitHub, you may notice that particular commenters have indicators informing you that they are either an "owner" or "collaborator". Collaborators are allowed to push commits, merge pull requests, and manage issues for a particular repository.

You may find yourself asking, "what is the point of all this?" Well, from a software development standpoint, managing shared code can become extremely difficult if source code management (SCM) is not used. Git, being a distributed version control system (DVCS), works best when there is a central repository that all developers push to and pull from. This remote repository (or simply *remote*) is often referred to as the "origin", since that is what Git names the first remote you add to your local copy of a repository.

To begin using GitHub, try checking out the [explore section](https://github.com/explore). There, you will find great projects that YOU can use and contribute to today!

Happy coding!

**Comment by andrewhamon** [comment]
> Git, being a distributed version control system (DVCS)...

> ...works best when there is a central repository...

But that takes the D out of DVCS
